import type { Metadata } from "next"
import { Geist, Geist_Mono, Inter } from "next/font/google"
import "./globals.css"
import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/providers/theme-provider"
import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "react-hot-toast"
import TanstackProvider from "@/components/providers/tanstack-provider"

const interHeading = Inter({ subsets: ["latin"], variable: "--font-heading" })

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" })

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning={true}
      className={cn(
        "h-full",
        "antialiased",
        geistMono.variable,
        "font-sans",
        geist.variable,
        interHeading.variable
      )}
    >
      <body className="flex min-h-full flex-col">
        <ThemeProvider>
          <Toaster position="top-center" reverseOrder={false} />
          <TooltipProvider>
            <TanstackProvider>{children}</TanstackProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
